/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.io.IOException;
/**
 *
 * @author 고상진
 */import javax.swing.*;               // GUI 컴포넌트를 위한 Swing 라이브러리
import javax.swing.table.DefaultTableModel; // JTable 모델을 사용하기 위한 라이브러리
import java.util.Date;              // 날짜 관련 기능을 위한 라이브러리
import java.text.SimpleDateFormat;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

public class Calendar1 extends javax.swing.JFrame {
    DB_MAN DBM = new DB_MAN();
    String strSQL = "";
    /**
     * Creates new form NewJFrame
     */
    public Calendar1() {
        initComponents();
        initializeTable();
                  
    }
    
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calendar = new com.toedter.calendar.JCalendar();
        titleField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        descriptionField = new javax.swing.JTextField();
        deleteButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        scheduleTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titleField.setText("제목을 입력하세요.");
        titleField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                titleFieldMouseClicked(evt);
            }
        });

        addButton.setText("입력");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        descriptionField.setText("내용을 입력하세요.");
        descriptionField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                descriptionFieldMouseClicked(evt);
            }
        });

        deleteButton.setText("삭제");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        updateButton.setText("수정");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        scheduleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scheduleTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scheduleTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(scheduleTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(calendar, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(updateButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteButton)))
                        .addGap(0, 4, Short.MAX_VALUE)))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calendar, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addButton)
                            .addComponent(updateButton)
                            .addComponent(deleteButton))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
          String title = titleField.getText();
          String description = descriptionField.getText();
          Date selectedDate = calendar.getDate();
 
    if (title.isEmpty()) {
        JOptionPane.showMessageDialog(this, "일정 제목을 입력하세요.");
        return;
    }

    // 날짜를 yyyy-MM-dd 형식으로 변환
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    int rowCount = scheduleTable.getRowCount();
    String formattedDate = dateFormat.format(selectedDate);
 try {
        DBM.dbOpen();
        strSQL = "INSERT INTO EVENT (event_no, event_date, event_title, event_content) " +
             "VALUES (" + (rowCount + 1) + ", '" + formattedDate + "', '" + title + "', '" + description + "')";
        
        DBM.stmt.executeUpdate(strSQL);
        DBM.dbClose();
        JOptionPane.showMessageDialog(this, "일정이 등록되었습니다.");
    } catch (Exception e) {
        System.out.println("SQLException:" + e.getMessage());
    }   
 
    // JTable에 일정 추가
    DefaultTableModel model = (DefaultTableModel) scheduleTable.getModel();
    model.addRow(new Object[]{rowCount + 1, formattedDate, title, description});

    // 입력 필드 초기화
    titleField.setText("");
    descriptionField.setText("");
        
            
    }//GEN-LAST:event_addButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        
          int selectedRow = scheduleTable.getSelectedRow();
    
    // 일정이 선택되지 않으면 알림
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "수정할 일정을 선택하세요.");
        return;
    }
    
    // 선택된 일정의 event_no 가져오기
    DefaultTableModel model = (DefaultTableModel) scheduleTable.getModel();
    int eventNo = (int) model.getValueAt(selectedRow, 0); // 첫 번째 열은 event_no
    
    // 입력 필드에서 제목, 내용, 날짜 가져오기
    String title = titleField.getText();
    String description = descriptionField.getText();
    Date selectedDate = calendar.getDate();
    
    // 날짜를 yyyy-MM-dd 형식으로 변환
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    String formattedDate = dateFormat.format(selectedDate);
    
    // DB 업데이트 쿼리
    try {
        DBM.dbOpen(); // DB 연결
        
        // UPDATE 쿼리 준비
        String strSQL = "UPDATE EVENT SET event_date = ?, event_title = ?, event_content = ? WHERE event_no = ?";
        
        // PreparedStatement 객체 생성
        PreparedStatement pstmt = DBM.con.prepareStatement(strSQL);
        pstmt.setString(1, formattedDate); // 날짜 설정
        pstmt.setString(2, title);         // 제목 설정
        pstmt.setString(3, description);   // 내용 설정
        pstmt.setInt(4, eventNo);          // 수정할 event_no 설정
        
        // 쿼리 실행
        int updatedRows = pstmt.executeUpdate(); // DB에서 업데이트 수행
        
        // 업데이트 성공 여부 확인
        if (updatedRows > 0) {
            // 테이블의 해당 행 업데이트
            model.setValueAt(formattedDate, selectedRow, 1);
            model.setValueAt(title, selectedRow, 2);
            model.setValueAt(description, selectedRow, 3);
            
            JOptionPane.showMessageDialog(this, "일정이 수정되었습니다.");
        } else {
            JOptionPane.showMessageDialog(this, "수정에 실패했습니다.");
        }
        
        DBM.dbClose(); // DB 연결 종료
    } catch (SQLException e) {
        System.out.println("SQLException: " + e.getMessage());
        JOptionPane.showMessageDialog(this, "수정 중 오류가 발생했습니다.");
    }   catch (IOException ex) {
            Logger.getLogger(Calendar1.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    // 입력 필드 초기화
    titleField.setText("");
    descriptionField.setText("");
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        
            int selectedRow = scheduleTable.getSelectedRow();
    
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "삭제할 일정을 선택하세요.");
        return;
    }
    
    // JTable에서 선택된 행의 event_no 값 가져오기
    DefaultTableModel model = (DefaultTableModel) scheduleTable.getModel();
    int eventNo = (int) model.getValueAt(selectedRow, 0); // 선택된 일정의 event_no

    // DB에서 해당 일정 삭제
    try {
        DBM.dbOpen(); // DB 연결 (conn이 올바르게 설정되어 있는지 확인)
        
        // DELETE 쿼리 준비
        String strSQL = "DELETE FROM EVENT WHERE event_no = ?";
        
        // PreparedStatement 객체 생성
        PreparedStatement pstmt = DBM.con.prepareStatement(strSQL);
        pstmt.setInt(1, eventNo); // 삭제할 일정의 event_no 값을 설정
        
        // 쿼리 실행
        int deletedRows = pstmt.executeUpdate(); // DB에서 삭제 수행
        if (deletedRows > 0) {
            // DB에서 삭제가 성공하면 JTable에서도 해당 행 삭제
            model.removeRow(selectedRow);
            JOptionPane.showMessageDialog(this, "일정이 삭제되었습니다.");
        } else {
            JOptionPane.showMessageDialog(this, "삭제에 실패했습니다.");
        }
        
        DBM.dbClose(); // DB 연결 종료
    } catch (Exception e) {
        System.out.println("SQLException: " + e.getMessage());
        JOptionPane.showMessageDialog(this, "삭제 중 오류가 발생했습니다.");
    }
    
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void scheduleTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scheduleTableMouseClicked
        // TODO add your handling code here:
            // 사용자가 선택한 행의 인덱스를 가져옴
    int selectedRow = scheduleTable.getSelectedRow();
    
    // 일정이 선택되지 않았을 경우
    if (selectedRow == -1) {
        return;
    }
    
    // 선택한 일정의 제목과 내용을 텍스트 필드에 설정
    DefaultTableModel model = (DefaultTableModel) scheduleTable.getModel();
    String title = (String) model.getValueAt(selectedRow, 2); // 제목 열의 데이터
    String description = (String) model.getValueAt(selectedRow, 3); // 내용 열의 데이터
    
    titleField.setText(title);         // 제목 필드에 설정
    descriptionField.setText(description); // 내용 필드에 설정
    }//GEN-LAST:event_scheduleTableMouseClicked

    private void titleFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleFieldMouseClicked
        // TODO add your handling code here:
        titleField.setText("");      
    }//GEN-LAST:event_titleFieldMouseClicked

    private void descriptionFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descriptionFieldMouseClicked
        // TODO add your handling code here:
        descriptionField.setText("");
    }//GEN-LAST:event_descriptionFieldMouseClicked
private void initializeTable() {
    DefaultTableModel model = new DefaultTableModel(new Object[]{"No", "날짜", "제목", "내용"}, 0);
    scheduleTable.setModel(model);
     // 테이블 열 크기 조정
    scheduleTable.getColumnModel().getColumn(0).setPreferredWidth(1);  // 번호 열 너비
    scheduleTable.getColumnModel().getColumn(1).setPreferredWidth(120); // 날짜 열 너비
    scheduleTable.getColumnModel().getColumn(2).setPreferredWidth(120); // 제목 열 너비
    scheduleTable.getColumnModel().getColumn(3).setPreferredWidth(300); // 내용 열 너비
    
        try {
        DBM.dbOpen();
       // strSQL = "SELECT * FROM EVENT ORDER BY event_no";
       //DBM.rs = DBM.stmt.executeQuery(strSQL);
        
        strSQL = "SELECT * FROM EVENT ORDER BY event_date"; //날짜순 정렬
        DBM.rs = DBM.stmt.executeQuery(strSQL);
        // DB에서 데이터를 읽어와 JTable에 추가
        while (DBM.rs.next()) {
            int no = DBM.rs.getInt("event_no");
            String date = DBM.rs.getString("event_date");
            String title = DBM.rs.getString("event_title");
            String content = DBM.rs.getString("event_content");
            model.addRow(new Object[]{no, date, title, content});
        }
        
        DBM.dbClose();
    } catch (Exception e) {
        System.out.println("SQLException: " + e.getMessage());
    }
        
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calendar1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calendar1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calendar1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calendar1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calendar1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private com.toedter.calendar.JCalendar calendar;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField descriptionField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable scheduleTable;
    private javax.swing.JTextField titleField;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
