
import java.util.Vector;
import java.util.stream.Collectors;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSetMetaData;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author chlgur
 */
DB_MAN DBM = new DB_MAN();
    String strSQL;
public class MainFrame extends javax.swing.JFrame {
    
    DB_MAN DBM = new DB_MAN();
    String strSQL;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jF_main = new javax.swing.JFrame();
        btn_manage1 = new javax.swing.JButton();
        btn_date1 = new javax.swing.JButton();
        btn_medical1 = new javax.swing.JButton();
        lbl_icon1 = new javax.swing.JLabel();
        jF_manage = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst_player = new javax.swing.JList<>();
        btn_addplayer = new javax.swing.JButton();
        btn_editplayer = new javax.swing.JButton();
        btn_searchplayer = new javax.swing.JButton();
        jF_editpalyer = new javax.swing.JFrame();
        lbl_editface = new javax.swing.JLabel();
        jf_editno = new javax.swing.JTextField();
        jf_editcbirth = new javax.swing.JTextField();
        jf_editname = new javax.swing.JTextField();
        jf_editfrom = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        ja_editrecord = new javax.swing.JTextArea();
        btn_del = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        jF_searchpalyer = new javax.swing.JFrame();
        lbl_searchface = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_searchpersonalinfo = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        ta_searchpersonalrecord = new javax.swing.JTextArea();
        jF_addpalyer = new javax.swing.JFrame();
        tf_addno = new javax.swing.JTextField();
        tf_addbirth = new javax.swing.JTextField();
        tf_addname = new javax.swing.JTextField();
        tf_editfrom = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        ta_addrecord = new javax.swing.JTextArea();
        btb_add = new javax.swing.JButton();
        btn_addface = new javax.swing.JButton();
        jF_date = new javax.swing.JFrame();
        jF_medical = new javax.swing.JFrame();
        jScrollPane6 = new javax.swing.JScrollPane();
        lst_medicalplayer = new javax.swing.JList<>();
        M_button1 = new javax.swing.JButton();
        M_button2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        M_Table = new javax.swing.JTable();
        M_edit = new javax.swing.JFrame();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lbl_maintxt = new javax.swing.JLabel();
        tf_id = new javax.swing.JTextField();
        tf_pw = new javax.swing.JTextField();
        btn_login = new javax.swing.JButton();

        jF_main.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jF_main.setResizable(false);
        jF_main.setSize(new java.awt.Dimension(400, 270));

        btn_manage1.setText("선수");

        btn_date1.setText("일정");

        btn_medical1.setText("의료");
        btn_medical1.setToolTipText("");

        lbl_icon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IC_FC.png"))); // NOI18N
        lbl_icon1.setToolTipText("");

        javax.swing.GroupLayout jF_mainLayout = new javax.swing.GroupLayout(jF_main.getContentPane());
        jF_main.getContentPane().setLayout(jF_mainLayout);
        jF_mainLayout.setHorizontalGroup(
            jF_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jF_mainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_icon1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jF_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jF_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btn_manage1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_date1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_medical1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jF_mainLayout.setVerticalGroup(
            jF_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jF_mainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jF_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_icon1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jF_mainLayout.createSequentialGroup()
                        .addComponent(btn_manage1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_date1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_medical1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jF_manage.setName("Manage"); // NOI18N

        jScrollPane1.setViewportView(lst_player);

        btn_addplayer.setText("등록");

        btn_editplayer.setText("수정");

        btn_searchplayer.setText("조회");

        javax.swing.GroupLayout jF_manageLayout = new javax.swing.GroupLayout(jF_manage.getContentPane());
        jF_manage.getContentPane().setLayout(jF_manageLayout);
        jF_manageLayout.setHorizontalGroup(
            jF_manageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jF_manageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jF_manageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_addplayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_searchplayer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(btn_editplayer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                .addContainerGap())
        );
        jF_manageLayout.setVerticalGroup(
            jF_manageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jF_manageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jF_manageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jF_manageLayout.createSequentialGroup()
                        .addComponent(btn_addplayer, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_editplayer, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_searchplayer, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbl_editface.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_editface.setIcon(new javax.swing.ImageIcon(getClass().getResource("/T_face.jpg"))); // NOI18N

        jf_editno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jf_editno.setText("등번호");

        jf_editcbirth.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jf_editcbirth.setText("생년월일");

        jf_editname.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jf_editname.setText("이름");

        jf_editfrom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jf_editfrom.setText("국적");

        ja_editrecord.setColumns(20);
        ja_editrecord.setRows(5);
        ja_editrecord.setText("기록 뭐 띄울거야???????????????????");
        jScrollPane4.setViewportView(ja_editrecord);

        btn_del.setText("삭제");

        btn_save.setText("저장");

        javax.swing.GroupLayout jF_editpalyerLayout = new javax.swing.GroupLayout(jF_editpalyer.getContentPane());
        jF_editpalyer.getContentPane().setLayout(jF_editpalyerLayout);
        jF_editpalyerLayout.setHorizontalGroup(
            jF_editpalyerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jF_editpalyerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jF_editpalyerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(jF_editpalyerLayout.createSequentialGroup()
                        .addComponent(lbl_editface, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jF_editpalyerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jF_editpalyerLayout.createSequentialGroup()
                                .addComponent(jf_editno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jf_editname, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                            .addGroup(jF_editpalyerLayout.createSequentialGroup()
                                .addGroup(jF_editpalyerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jf_editcbirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jf_editfrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jF_editpalyerLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_del, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jF_editpalyerLayout.setVerticalGroup(
            jF_editpalyerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jF_editpalyerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jF_editpalyerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jF_editpalyerLayout.createSequentialGroup()
                        .addGroup(jF_editpalyerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jf_editno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jf_editname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(jf_editcbirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jf_editfrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_editface))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jF_editpalyerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_del)
                    .addComponent(btn_save))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbl_searchface.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_searchface.setIcon(new javax.swing.ImageIcon(getClass().getResource("/T_face.jpg"))); // NOI18N

        ta_searchpersonalinfo.setColumns(20);
        ta_searchpersonalinfo.setRows(5);
        jScrollPane2.setViewportView(ta_searchpersonalinfo);

        ta_searchpersonalrecord.setColumns(20);
        ta_searchpersonalrecord.setRows(5);
        jScrollPane3.setViewportView(ta_searchpersonalrecord);

        javax.swing.GroupLayout jF_searchpalyerLayout = new javax.swing.GroupLayout(jF_searchpalyer.getContentPane());
        jF_searchpalyer.getContentPane().setLayout(jF_searchpalyerLayout);
        jF_searchpalyerLayout.setHorizontalGroup(
            jF_searchpalyerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jF_searchpalyerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jF_searchpalyerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jF_searchpalyerLayout.createSequentialGroup()
                        .addComponent(lbl_searchface, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jF_searchpalyerLayout.setVerticalGroup(
            jF_searchpalyerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jF_searchpalyerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jF_searchpalyerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_searchface, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tf_addno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_addno.setText("등번호");

        tf_addbirth.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_addbirth.setText("생년월일");

        tf_addname.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf_addname.setText("이름");

        tf_editfrom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_editfrom.setText("국적");

        ta_addrecord.setColumns(20);
        ta_addrecord.setRows(5);
        ta_addrecord.setText("기록 뭐 띄울거야???????????????????");
        jScrollPane5.setViewportView(ta_addrecord);

        btb_add.setText("등록");

        btn_addface.setIcon(new javax.swing.ImageIcon(getClass().getResource("/T_face.jpg"))); // NOI18N

        javax.swing.GroupLayout jF_addpalyerLayout = new javax.swing.GroupLayout(jF_addpalyer.getContentPane());
        jF_addpalyer.getContentPane().setLayout(jF_addpalyerLayout);
        jF_addpalyerLayout.setHorizontalGroup(
            jF_addpalyerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jF_addpalyerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jF_addpalyerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jF_addpalyerLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btb_add, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jF_addpalyerLayout.createSequentialGroup()
                        .addComponent(btn_addface, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jF_addpalyerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jF_addpalyerLayout.createSequentialGroup()
                                .addComponent(tf_addno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_addname, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                            .addGroup(jF_addpalyerLayout.createSequentialGroup()
                                .addGroup(jF_addpalyerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_editfrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_addbirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jF_addpalyerLayout.setVerticalGroup(
            jF_addpalyerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jF_addpalyerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jF_addpalyerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_addface, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jF_addpalyerLayout.createSequentialGroup()
                        .addGroup(jF_addpalyerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_addname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_addno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(tf_addbirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tf_editfrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btb_add)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jF_dateLayout = new javax.swing.GroupLayout(jF_date.getContentPane());
        jF_date.getContentPane().setLayout(jF_dateLayout);
        jF_dateLayout.setHorizontalGroup(
            jF_dateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jF_dateLayout.setVerticalGroup(
            jF_dateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        lst_medicalplayer.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lst_medicalplayerAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane6.setViewportView(lst_medicalplayer);

        M_button1.setBackground(new java.awt.Color(204, 204, 255));
        M_button1.setText("수정");
        M_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_button1ActionPerformed(evt);
            }
        });

        M_button2.setBackground(new java.awt.Color(204, 204, 255));
        M_button2.setText("삭제");
        M_button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_button2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("맑은 고딕", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Medical Center");
        jLabel1.setToolTipText("");

        M_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "등번호", "부상상태", "부상날짜", "완치 예정일"
            }
        ));
        M_Table.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                M_TableAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane8.setViewportView(M_Table);

        javax.swing.GroupLayout jF_medicalLayout = new javax.swing.GroupLayout(jF_medical.getContentPane());
        jF_medical.getContentPane().setLayout(jF_medicalLayout);
        jF_medicalLayout.setHorizontalGroup(
            jF_medicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jF_medicalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jF_medicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jF_medicalLayout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jF_medicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jF_medicalLayout.createSequentialGroup()
                                .addComponent(M_button1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(M_button2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jF_medicalLayout.setVerticalGroup(
            jF_medicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jF_medicalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jF_medicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jF_medicalLayout.createSequentialGroup()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jF_medicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(M_button1)
                            .addComponent(M_button2)))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel2.setText("등번호");

        jLabel3.setText("부상 정보");

        jLabel4.setText("부상 날짜");

        jLabel5.setText("완치 날짜");

        jTextField4.setToolTipText("");

        jButton1.setText("추가 및 수정");

        javax.swing.GroupLayout M_editLayout = new javax.swing.GroupLayout(M_edit.getContentPane());
        M_edit.getContentPane().setLayout(M_editLayout);
        M_editLayout.setHorizontalGroup(
            M_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(M_editLayout.createSequentialGroup()
                .addGroup(M_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(M_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(M_editLayout.createSequentialGroup()
                            .addGroup(M_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(M_editLayout.createSequentialGroup()
                                    .addGap(3, 3, 3)
                                    .addComponent(jLabel2))
                                .addGroup(M_editLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel3))
                                .addGroup(M_editLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel5)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(M_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField1)
                                .addComponent(jTextField2)
                                .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)))
                        .addGroup(M_editLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField3))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        M_editLayout.setVerticalGroup(
            M_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(M_editLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(M_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(M_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(M_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(M_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 270));
        setSize(new java.awt.Dimension(400, 270));

        lbl_maintxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_maintxt.setText("구단 관리 시스템 로그인");

        tf_id.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        tf_pw.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf_pw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_pwActionPerformed(evt);
            }
        });

        btn_login.setText("Login");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_maintxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_pw, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                    .addComponent(tf_id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_login)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_maintxt)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(tf_pw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_pwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_pwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_pwActionPerformed

    private void M_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_button1ActionPerformed
        // TODO add your handling code here:
        M_edit.setVisible(true);
    }//GEN-LAST:event_M_button1ActionPerformed

    private void M_button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_button2ActionPerformed
        // TODO add your handling code here:
        
        }
    
    }//GEN-LAST:event_M_button2ActionPerformed

    private void lst_medicalplayerAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lst_medicalplayerAncestorAdded
        // TODO add your handling code here:
        // TODO add your handling code here:
       
        try{
            DBM.dbOpen();
            DBM.rs = DBM.stmt.executeQuery("Select UNIFORM_NUM, NAME From personal_info");
            Vector resultVC = new Vector();
            while(DBM.rs.next()){    
                String result = DBM.rs.getString("UNIFORM_NUM")+" "+DBM.rs.getString("NAME");
                resultVC.addElement(result);
            }
            lst_medicalplayer.setListData(resultVC);
            DBM.dbClose();
        }catch(Exception e){
            System.out.print(e.getMessage());
        }

        
    }//GEN-LAST:event_lst_medicalplayerAncestorAdded

    private void M_TableAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_M_TableAncestorAdded
        
// TODO add your handling code here:
         // JTable에 데이터를 표시할 기본 모델
            DefaultTableModel tableModel = new DefaultTableModel();
            M_Table.setModel(tableModel);
            try{
            DBM.dbOpen();
            DBM.rs = DBM.stmt.executeQuery("Select * From health_stat");
            ResultSetMetaData metaData = DBM.rs.getMetaData();
            int columnCount = metaData.getColumnCount();
        // 테이블 모델의 컬럼 헤더 설정
        tableModel.setColumnCount(0);  // 기존 컬럼 지우기
        for (int i = 1; i <= columnCount; i++) {
            tableModel.addColumn(metaData.getColumnLabel(i));  // 컬럼 헤더 추가
        }

        // 데이터 행을 테이블 모델에 추가
        while (DBM.rs.next()) {
            Object[] rowData = new Object[columnCount];
            for (int i = 1; i <= columnCount; i++) {
                rowData[i - 1] = DBM.rs.getObject(i);  // 각 컬럼 값을 가져와서 배열에 저장
            }
            tableModel.addRow(rowData);  // 행 추가
        }

        // DB 연결 종료
        DBM.dbClose();  // DB 연결 종료 메서드 호출 (예시)
        
        }catch(Exception e){
            System.out.print(e.getMessage());
        }        
    }//GEN-LAST:event_M_TableAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable M_Table;
    private javax.swing.JButton M_button1;
    private javax.swing.JButton M_button2;
    private javax.swing.JFrame M_edit;
    private javax.swing.JButton btb_add;
    private javax.swing.JButton btn_addface;
    private javax.swing.JButton btn_addplayer;
    private javax.swing.JButton btn_date1;
    private javax.swing.JButton btn_del;
    private javax.swing.JButton btn_editplayer;
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_manage1;
    private javax.swing.JButton btn_medical1;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_searchplayer;
    private javax.swing.JButton jButton1;
    private javax.swing.JFrame jF_addpalyer;
    private javax.swing.JFrame jF_date;
    private javax.swing.JFrame jF_editpalyer;
    private javax.swing.JFrame jF_main;
    private javax.swing.JFrame jF_manage;
    private javax.swing.JFrame jF_medical;
    private javax.swing.JFrame jF_searchpalyer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextArea ja_editrecord;
    private javax.swing.JTextField jf_editcbirth;
    private javax.swing.JTextField jf_editfrom;
    private javax.swing.JTextField jf_editname;
    private javax.swing.JTextField jf_editno;
    private javax.swing.JLabel lbl_editface;
    private javax.swing.JLabel lbl_icon1;
    private javax.swing.JLabel lbl_maintxt;
    private javax.swing.JLabel lbl_searchface;
    private javax.swing.JList<String> lst_medicalplayer;
    private javax.swing.JList<String> lst_player;
    private javax.swing.JTextArea ta_addrecord;
    private javax.swing.JTextArea ta_searchpersonalinfo;
    private javax.swing.JTextArea ta_searchpersonalrecord;
    private javax.swing.JTextField tf_addbirth;
    private javax.swing.JTextField tf_addname;
    private javax.swing.JTextField tf_addno;
    private javax.swing.JTextField tf_editfrom;
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_pw;
    // End of variables declaration//GEN-END:variables

